### ISSUE TITLE
Quill Not Defined

### ISSUE THREAD

**Issue by abbasmashaddy72** [rawilk/laravel-form-components#67]
### Laravel Form Components Version

7.1

### Laravel Version

9.19

### Alpine Version

3.4.2

### Bug description

Errors:
Uncaught ReferenceError: quill is not defined

Uncaught ReferenceError: value is not defined

Warning:
Alpine Expression Error: quill is not defined

Alpine Expression Error: value is not defined

### Steps to reproduce

Installed Latest Laravel Project using with vite

Followed the instruction given in Docs.

Tried 2 Methods of import of quill, but none works, same issue returns

Please Check for logs Below
Please Not I am not using the Vue it is just the extension from Chrome.

[npc.test-1669704065994.log](https://github.com/rawilk/laravel-form-components/files/10110407/npc.test-1669704065994.log)

### Relevant log output

```shell
The Log Output File has been Provided Above.
```

**Comment by tweekah** [comment]
Having the same issue, any fixes jet?

**Comment by tweekah** [comment]
Problem is with webpack, L9 uses vite as default so form-components.js is not loaded.

**Comment by tweekah** [comment]
Seem to have found a solution for now; add `'./vendor/rawilk/laravel-form-components/dist/form-components.js',` to the laravel input plugins of your vite config

**Comment by rawilk** [comment]
You shouldn't need to resort to adding the package's JS files to your build pipeline, even in v7. I've never had an issue myself loading the package's scripts alongside of using vite in a laravel app.

I've released v8 of the package today, which I know for sure works in a Laravel 10.x app that uses vite, since I used a brand new app to test it out as I was developing the new release. I've also changed the build process for the package's scripts from webpack to rollup, but that really shouldn't make a difference.

I'm going to close this issue, but feel free to re-open if you're still having issues with this.
